framework:

    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation


            command_bus:
                 # disable the default middleware
                default_middleware: false

                # and/or add your own
                middleware:
                    # service ids that implement Symfony\Component\Messenger\Middleware\MiddlewareInterface
                    - 'App\Middleware\MyMiddleware'
                    - doctrine_ping_connection
                    - doctrine_transaction
                    - router_context
                    - validation


        reset_on_message: true
        failure_transport: failed_default

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60
                retry_strategy:
                    max_retries: 3
                    multiplier: 1
                serializer: messenger.transport.symfony_serializer

            async_hight:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                serializer: messenger.transport.symfony_serializer

            failed_default: 'doctrine://default?queue_name=failed_default'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\TestMessage: async
            App\Message\SmsNotification: async_hight
            App\Message\OtherSmsNotification:  async 
            # App\Message\NewUserWelcomeEmail: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
